<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$displayData=$this->item;
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

use Joomla\Registry\Registry;
JLoader::register('TagsHelperRoute', JPATH_BASE . '/components/com_tags/helpers/route.php');
$authorised = JFactory::getUser()->getAuthorisedViewLevels();
// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');
?>
<div id="post_detail" class="content">
    <div class="tag_header">
        <span>文章详情</span>
        <form action="//google.com/search" method="get" target="_blank" class="search">
            <div class="search_box">
                <input type="text" name="q" class="search_input">
                <input type="hidden" name="q" value="site:tech.meituan.com">
                <input type="hidden" name="gw_rd" value="cr">
                <input type="submit" id="search_submit">
                <label for="search_submit"></label>
            </div>
        </form>
    </div>

    <article class="detail_post">
        <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
        <?php if ($this->params->get('show_page_heading')) : ?>
            <div class="page-header">
                <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
            </div>
        <?php endif;
        if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
        {
            echo $this->item->pagination;
        }
        ?>

        <?php // Todo Not that elegant would be nice to group the params ?>
        <?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
            || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

        <?php if (!$useDefList && $this->print) : ?>
            <div id="pop-print" class="btn hidden-print">
                <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
            </div>
            <div class="clearfix"> </div>
        <?php endif; ?>
        <?php if ($params->get('show_title') || $params->get('show_author')) : ?>
            <header class="article__title">
                <?php if ($params->get('show_title')) : ?>
                    <h1 class="title">
                        <?php echo $this->escape($this->item->title); ?>
                    </h1>
                <?php endif; ?>
                <p class="info">

                    <?php $author = ($displayData->created_by_alias ?: $displayData->author); ?>
                    <?php $author = '<span class="nick">' . $author . '</span>'; ?>
                    <?php if (!empty($displayData->contact_link ) && $displayData['params']->get('link_author') == true) : ?>
                        <?php echo JText::sprintf('%s', JHtml::_('link', $displayData->contact_link, $author, array('itemprop' => 'url'))); ?>
                    <?php else : ?>
                        <?php echo JText::sprintf('%s', $author); ?>
                    <?php endif; ?>
                    <span class="Separate"> ·</span>

                    <span class="date"><?php echo JText::sprintf('%s', JHtml::_('date', $displayData->publish_up, JText::_('DATE_FORMAT_LC3'))); ?></span>
                </p>
            </header>
        <?php endif; ?>
        <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
        <?php echo $this->item->event->afterDisplayTitle; ?>
        <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
        <?php echo $this->item->event->beforeDisplayContent; ?>
        <div class="article__content">
            <?php echo $this->item->text; ?>
            <div class="hidden-mobile">
                <br>
                <br>
                <br>
                <p>
                    <strong>发现文章有错误、对内容有疑问，都可以关注美团技术团队微信公众号（meituantech），在后台给我们留言。我们每周会挑选出一位热心小伙伴，送上一份精美的小礼品。快来扫码关注我们吧！</strong></p>
                <div class="article__footer__img">
                    <img src="https://tech.meituan.com/img/meituanjishutuandui.png" width="455" alt="公众号二维码" align="center">
                </div>
            </div>
        </div>
        <footer class="article__footer">
            <div class="meta article__meta">
                <?php if (!empty($displayData->tags->itemTags)) : ?>
                    <?php foreach ($displayData->tags->itemTags as $i => $tag) : ?>
                        <?php if (in_array($tag->access, $authorised)) : ?>
                            <?php $tagParams = new Registry($tag->params); ?>
                            <?php $link_class = $tagParams->get('tag_link_class', 'label label-info'); ?>
                            <a href="<?php echo JRoute::_(TagsHelperRoute::getTagRoute($tag->tag_id . ':' . $tag->alias)); ?>" class="tag"><span class="tag_name"> <?php echo $this->escape($tag->title); ?></span></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </footer>
    </article>
</div>