<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$displayData=$this->item;
$params = $this->item->params;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');

use Joomla\Registry\Registry;
JLoader::register('TagsHelperRoute', JPATH_BASE . '/components/com_tags/helpers/route.php');
$authorised = JFactory::getUser()->getAuthorisedViewLevels();
?>
    <header class="post-title">
        <?php if ($params->get('link_titles') && ($params->get('access-view') || $params->get('show_noauth', '0') == '1')) : ?>
            <a href="<?php echo JRoute::_(
                ContentHelperRoute::getArticleRoute($displayData->slug, $displayData->catid, $displayData->language)
            ); ?>" itemprop="url"><?php echo $this->escape($displayData->title); ?></a>
        <?php else : ?>
            <?php echo $this->escape($displayData->title); ?>
        <?php endif; ?>
    </header>
    <div class="post-meta">
        <?php $author = ($displayData->created_by_alias ?: $displayData->author); ?>
        <?php $author = '<span class="post-meta-author">' . $author . '</span>'; ?>
        <?php if (!empty($displayData->contact_link ) && $displayData['params']->get('link_author') == true) : ?>
            <?php echo JText::sprintf('%s', JHtml::_('link', $displayData->contact_link, $author, array('itemprop' => 'url'))); ?>
        <?php else : ?>
            <?php echo JText::sprintf('%s', $author); ?>
        <?php endif; ?>
        <span class="post-meta-ctime"><?php echo JText::sprintf('%s', JHtml::_('date', $displayData->publish_up, JText::_('DATE_FORMAT_LC3'))); ?></span>
    </div>
<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
<?php echo $this->item->event->beforeDisplayContent; ?>
<?php echo $this->item->introtext; ?>
<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?>
<footer class="post-tags">
    <?php if (!empty($displayData->tags->itemTags)) : ?>
        <?php foreach ($displayData->tags->itemTags as $i => $tag) : ?>
            <?php if (in_array($tag->access, $authorised)) : ?>
                <?php $tagParams = new Registry($tag->params); ?>
                <?php $link_class = $tagParams->get('tag_link_class', 'label label-info'); ?>
                <a href="<?php echo JRoute::_(TagsHelperRoute::getTagRoute($tag->tag_id . ':' . $tag->alias)); ?>" class="tag"><span class="tag_name"> <?php echo $this->escape($tag->title); ?></span></a>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</footer>
