<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_tags
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::_('behavior.core');
JHtml::_('formbehavior.chosen', 'select');


// Get the user object.
$user = JFactory::getUser();

// Check if user is allowed to add/edit based on tags permissions.
// Do we really have to make it so people can see unpublished tags???
$canEdit      = $user->authorise('core.edit', 'com_tags');
$canCreate    = $user->authorise('core.create', 'com_tags');
$canEditState = $user->authorise('core.edit.state', 'com_tags');

?>
	<?php if (empty($this->items)) : ?>
		<p><?php echo JText::_('COM_TAGS_NO_ITEMS'); ?></p>
	<?php else : ?>
			<?php foreach ($this->items as $i => $item) : ?>
            <article class="post post-with-tags">
                <header class="post-title">
                    <a href="<?php echo JRoute::_($item->link); ?>" itemprop="url">
                        <?php echo $this->escape($item->core_title); ?>
                    </a>
                </header>
                <div class="post-meta">
                    <?php $author = ($item->created_by_alias ?: $item->author); ?>
                    <?php $author = '<span class="post-meta-author">' . $author . '</span>'; ?>
                    <?php if (!empty($item->contact_link ) && $item['params']->get('link_author') == true) : ?>
                        <?php echo JText::sprintf('%s', JHtml::_('link', $item->contact_link, $author, array('itemprop' => 'url'))); ?>
                    <?php else : ?>
                        <?php echo JText::sprintf('%s', $author); ?>
                    <?php endif; ?>
                    <span class="post-meta-ctime"><?php echo JText::sprintf('%s', JHtml::_('date', $item->publish_up, JText::_('DATE_FORMAT_LC3'))); ?></span>
                </div>
                <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
                <?php echo $item->event->beforeDisplayContent; ?>
                <?php echo $item->text; ?>
                <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
                <?php echo $item->event->afterDisplayContent; ?>
                <footer class="post-tags">
                    <?php if (!empty($item->tags->itemTags)) : ?>
                        <?php foreach ($item->tags->itemTags as $i => $tag) : ?>
                            <?php if (in_array($tag->access, $authorised)) : ?>
                                <?php $tagParams = new Registry($tag->params); ?>
                                <?php $link_class = $tagParams->get('tag_link_class', 'label label-info'); ?>
                                <a href="<?php echo JRoute::_(TagsHelperRoute::getTagRoute($tag->tag_id . ':' . $tag->alias)); ?>" class="tag"><span class="tag_name"> <?php echo $this->escape($tag->title); ?></span></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </footer>
			<?php endforeach; ?>
	<?php endif; ?>
